"""add parent child chunks and ingestion metadata

Revision ID: 81dd2eefce0f
Revises: add_evaluation_benchmark_tables
Create Date: 2026-07-08 15:04:43.610785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81dd2eefce0f'
down_revision: Union[str, None] = 'add_evaluation_benchmark_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_ingestion_metadata',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parser_name', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('fallback_usage_count', sa.Integer(), nullable=False),
    sa.Column('overlap_usage_count', sa.Integer(), nullable=False),
    sa.Column('parsing_duration_seconds', sa.Float(), nullable=False),
    sa.Column('chunking_duration_seconds', sa.Float(), nullable=False),
    sa.Column('mapping_duration_seconds', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_ingestion_metadata_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_ingestion_metadata')),
    sa.UniqueConstraint('document_id', name=op.f('uq_document_ingestion_metadata_document_id'))
    )
    op.create_table('document_parent_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('block_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('block_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('page_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_orders', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hierarchy_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parser_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structure_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_parent_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_parent_chunks'))
    )
    op.create_table('document_child_chunks',
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('block_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('block_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('page_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_orders', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hierarchy_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parser_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structure_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_child_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_parent_chunks.id'], name=op.f('fk_document_child_chunks_parent_id_document_parent_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_child_chunks'))
    )
    op.drop_index('ix_benchmark_datasets_org_created', table_name='benchmark_datasets')
    op.drop_index('ix_conversations_org_user_updated', table_name='conversations')
    op.drop_index('ix_documents_organization_id', table_name='documents')
    op.drop_index('ix_documents_stored_file_name', table_name='documents')
    op.drop_index('ix_documents_uploaded_by_user_id', table_name='documents')
    op.create_unique_constraint(op.f('uq_documents_stored_file_name'), 'documents', ['stored_file_name'])
    op.drop_index('ix_evaluation_results_org_created', table_name='evaluation_results')
    op.drop_index('ix_evaluation_results_run_id', table_name='evaluation_results')
    op.drop_index('ix_evaluation_runs_org_created', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_status', table_name='evaluation_runs')
    op.drop_index('ix_ingestion_jobs_document_id', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_organization_id', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_status', table_name='ingestion_jobs')
    op.drop_index('uq_ingestion_jobs_document_active', table_name='ingestion_jobs', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying])::text[]))")
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.create_unique_constraint(op.f('uq_organizations_slug'), 'organizations', ['slug'])
    op.drop_index('ix_roles_role_name', table_name='roles')
    op.create_unique_constraint(op.f('uq_roles_role_name'), 'roles', ['role_name'])
    op.drop_index('ix_users_clerk_user_id', table_name='users')
    op.drop_index('ix_users_email_address', table_name='users')
    op.drop_index('ix_users_organization_id', table_name='users')
    op.create_unique_constraint(op.f('uq_users_clerk_user_id'), 'users', ['clerk_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_clerk_user_id'), 'users', type_='unique')
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_index('ix_users_email_address', 'users', ['email_address'], unique=False)
    op.create_index('ix_users_clerk_user_id', 'users', ['clerk_user_id'], unique=True)
    op.drop_constraint(op.f('uq_roles_role_name'), 'roles', type_='unique')
    op.create_index('ix_roles_role_name', 'roles', ['role_name'], unique=True)
    op.drop_constraint(op.f('uq_organizations_slug'), 'organizations', type_='unique')
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=True)
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('uq_ingestion_jobs_document_active', 'ingestion_jobs', ['document_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying])::text[]))")
    op.create_index('ix_ingestion_jobs_status', 'ingestion_jobs', ['status'], unique=False)
    op.create_index('ix_ingestion_jobs_organization_id', 'ingestion_jobs', ['organization_id'], unique=False)
    op.create_index('ix_ingestion_jobs_document_id', 'ingestion_jobs', ['document_id'], unique=False)
    op.create_index('ix_evaluation_runs_status', 'evaluation_runs', ['organization_id', 'status'], unique=False)
    op.create_index('ix_evaluation_runs_org_created', 'evaluation_runs', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_evaluation_results_run_id', 'evaluation_results', ['run_id'], unique=False)
    op.create_index('ix_evaluation_results_org_created', 'evaluation_results', ['organization_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('uq_documents_stored_file_name'), 'documents', type_='unique')
    op.create_index('ix_documents_uploaded_by_user_id', 'documents', ['uploaded_by_user_id'], unique=False)
    op.create_index('ix_documents_stored_file_name', 'documents', ['stored_file_name'], unique=True)
    op.create_index('ix_documents_organization_id', 'documents', ['organization_id'], unique=False)
    op.create_index('ix_conversations_org_user_updated', 'conversations', ['organization_id', 'user_id', 'updated_at'], unique=False)
    op.create_index('ix_benchmark_datasets_org_created', 'benchmark_datasets', ['organization_id', 'created_at'], unique=False)
    op.drop_table('document_child_chunks')
    op.drop_table('document_parent_chunks')
    op.drop_table('document_ingestion_metadata')
    # ### end Alembic commands ###
