"""Defines the DocChunk Pydantic model representing a structured document chunk."""

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class DocChunk(BaseModel):
    """Represents a structured document chunk generated by the chunking engine.

    Holds the text segment content along with consolidated block-level metadata
    to enable parent-child retrieval and context engineering in downstream modules.
    """

    model_config = ConfigDict(frozen=True)

    text: str = Field(
        ...,
        description="The normalized text content of this chunk.",
    )
    document_id: UUID = Field(
        ...,
        description="The unique identifier of the source document.",
    )
    block_ids: list[str] = Field(
        default_factory=list,
        description="The list of source block IDs included in this chunk.",
    )
    block_types: list[str] = Field(
        default_factory=list,
        description="The list of block types corresponding to each block in the chunk.",
    )
    page_numbers: list[int] = Field(
        default_factory=list,
        description="The list of page numbers associated with the blocks.",
    )
    source_orders: list[int] = Field(
        default_factory=list,
        description="The list of block source_order values.",
    )
    hierarchy_levels: list[int] = Field(
        default_factory=list,
        description="The list of block hierarchy levels.",
    )
    parser_version: str = Field(
        ...,
        description="The version of the parser used to parse the document.",
    )
    schema_version: str = Field(
        ...,
        description="The schema version of the canonical representation.",
    )
    parser_confidence: list[float] = Field(
        default_factory=list,
        description="The list of parser confidence scores for each block.",
    )
    structure_confidence: list[float] = Field(
        default_factory=list,
        description="The list of structure detection confidence scores for each block.",
    )
    parent_id: UUID | None = Field(
        default=None,
        description="The unique identifier of this chunk when acting as a parent.",
    )
    child_ids: list[UUID] = Field(
        default_factory=list,
        description="The unique identifiers of any associated child chunks.",
    )

    # Hierarchical and metadata fields for Phase 23
    section_id: UUID | None = Field(
        default=None,
        description="The unique section identifier this chunk belongs to.",
    )
    section_title: str | None = Field(
        default=None,
        description="The heading/section title this chunk belongs to.",
    )
    chunk_index: int = Field(
        default=0,
        description="The sequential index of the chunk in the document.",
    )
    chunk_hash: str = Field(
        default="",
        description="The SHA-256 hash of the normalized chunk content.",
    )
    ingestion_version: str = Field(
        default="1.0.0",
        description="The ingestion version configured at the time of processing.",
    )
    workspace_id: UUID | None = Field(
        default=None,
        description="The workspace identifier (mapped to organization_id).",
    )
